export type UiLanguage = 'en' | 'pt';

const PT_LABELS: Record<string, string> = {
  'Skip to prompt builder': 'Ir para o construtor de prompts',
  'Built for GPT-6 Astra': 'Feito para o GPT-6 Astra',
  'Interface language': 'Idioma da interface',
  'Switch interface to English': 'Mudar a interface para inglês',
  'Switch interface to Portuguese': 'Mudar a interface para português',
  'Edit generated prompt': 'Editar prompt gerado',
  'How it works': 'Como funciona',
  'FROM INTENT TO INSTRUCTION': 'DA INTENÇÃO À INSTRUÇÃO',
  'Give your idea a ': 'Dê uma direção ',
  'clear direction.': 'clara à sua ideia.',
  'No API key needed.': 'Nenhuma chave de API necessária.',
  'Describe what you want to do. Build a prompt that tells Astra what success looks like.':
    'Descreva o que você quer fazer. Crie um prompt que diga ao Astra como é o sucesso.',
  'Your brief stays in this tab.': 'Seu briefing fica nesta aba.',
  'A brief in. A ready-to-use prompt out.':
    'Um briefing entra. Um prompt pronto sai.',
  'Close guide': 'Fechar guia',
  'Describe the outcome': 'Descreva o resultado',
  'Start with your goal. Add context and a definition of done when they matter.':
    'Comece pelo objetivo. Acrescente contexto e critérios de conclusão quando forem importantes.',
  'Shape the instructions': 'Ajuste as instruções',
  'Local rules detect a likely deliverable and apply your restrictions. Correct the category or deliverable when needed; detection is a heuristic.':
    'Regras locais detectam uma entrega provável e aplicam suas restrições. Corrija a categoria ou a entrega quando necessário; a detecção é heurística.',
  'Use it with Astra': 'Use com o Astra',
  'Review, edit and copy the prompt into your GPT-6 Astra session. This app builds prompts; it does not call a model or run your project.':
    'Revise, edite e copie o prompt para sua sessão do GPT-6 Astra. Este app cria prompts; ele não chama um modelo nem executa seu projeto.',
  'Astra API setup:': 'Configuração da API do Astra:',
  'Use gpt-6-astra with the Responses API for tool calling. Choose reasoning effort from low to max; none and minimal are unsupported. Remove temperature, top_p, top_logprobs and logprobs.':
    'Use gpt-6-astra com a Responses API para chamadas de ferramentas. Escolha o nível de raciocínio entre low e max; none e minimal não são compatíveis. Remova temperature, top_p, top_logprobs e logprobs.',
  'Experimental notes:': 'Notas experimentais:',
  'The supplied completion-gate and stop-hook recipes are treated as architecture ideas, not guaranteed model behavior or required OpenAI configuration.':
    'As receitas fornecidas de validação da conclusão e stop hook são tratadas como ideias de arquitetura, não como comportamento garantido do modelo ou configuração obrigatória da OpenAI.',
  'Based on the': 'Baseado no',
  'official OpenAI model guide': 'guia oficial de modelos da OpenAI',
  'and the supplied Rahul / @sairahul1 masterclass and Astra engineering notes. Guidance reviewed September 9, 2026. The instruction scaffold stays in English; the requested answer language follows your brief or language setting. Templates are starting points, not a guarantee of model performance. Independent tool; not affiliated with OpenAI.':
    'na masterclass fornecida de Rahul / @sairahul1 e nas notas de engenharia do Astra. Orientações revisadas em 9 de setembro de 2026. A estrutura do prompt permanece em inglês; o idioma da resposta segue seu briefing ou a configuração de idioma. Os templates são pontos de partida, sem garantia de desempenho do modelo. Ferramenta independente; não afiliada à OpenAI.',
  'Your brief': 'Seu briefing',
  'A little context goes a long way': 'Um pouco de contexto ajuda muito',
  'What are you working on?': 'Em que você está trabalhando?',
  'What do you want Astra to do?': 'O que você quer que o Astra faça?',
  'e.g. Build a webapp that helps freelancers estimate project costs and create a clear quote…':
    'ex.: Crie um webapp que ajude freelancers a estimar custos e montar um orçamento claro…',
  'Describe the result you need. Write naturally, in any language.':
    'Descreva o resultado que você precisa. Escreva naturalmente, em qualquer idioma.',
  'Try an idea': 'Experimente uma ideia',
  'Useful context': 'Contexto útil',
  optional: 'opcional',
  'Who is this for? What facts, constraints or background should Astra know?':
    'Para quem é isso? Que fatos, restrições ou contexto o Astra deve conhecer?',
  'Requirements & definition of done': 'Requisitos e definição de concluído',
  Requirements: 'Requisitos',
  'Must-haves, limits, tone, audience or things to avoid…':
    'Itens obrigatórios, limites, tom, público ou coisas a evitar…',
  'What does done look like?': 'Como saberemos que está concluído?',
  'e.g. The mobile form works, totals are correct, and the quote can be copied.':
    'ex.: O formulário funciona no celular, os totais estão corretos e o orçamento pode ser copiado.',
  'Make it fit': 'Ajuste o prompt',
  'Prompt structure': 'Estrutura do prompt',
  'Adaptive · smallest useful structure': 'Adaptativa · menor estrutura útil',
  'Compact · merged sections': 'Compacta · seções combinadas',
  'Expanded · explicit sections': 'Expandida · seções explícitas',
  'Astra’s autonomy': 'Autonomia do Astra',
  Balanced: 'Equilibrada',
  'Take initiative': 'Tomar iniciativa',
  'Clarify first': 'Esclarecer primeiro',
  'Requested deliverable': 'Entrega solicitada',
  'Follow the brief': 'Seguir o briefing',
  Detected: 'Detectada',
  Selected: 'Selecionada',
  'Detection uses local rules.': 'A detecção usa regras locais.',
  'Review these settings': 'Revise estas configurações',
  'Only recognized patterns are checked. Review the complete prompt.':
    'Somente padrões reconhecidos são verificados. Revise o prompt completo.',
  'Output & available tools': 'Formato e ferramentas disponíveis',
  'Response format': 'Formato da resposta',
  'Match the task': 'Combinar com a tarefa',
  'Plain paragraphs': 'Parágrafos corridos',
  'Numbered steps': 'Passos numerados',
  'Comparison table': 'Tabela comparativa',
  'Response length': 'Tamanho da resposta',
  Concise: 'Concisa',
  Detailed: 'Detalhada',
  'Tools available in your Astra session':
    'Ferramentas disponíveis na sua sessão do Astra',
  'Unknown · discover in target session':
    'Desconhecidas · descobrir na sessão de destino',
  'No tools available': 'Nenhuma ferramenta disponível',
  'Web search declared available': 'Busca na web declarada disponível',
  'Workspace declared available': 'Workspace declarado disponível',
  'Subagents declared available': 'Subagentes declarados disponíveis',
  'These are unverified availability hints, not permissions. Other capabilities stay unknown.':
    'São indicações de disponibilidade não verificadas, não permissões. As outras capacidades continuam desconhecidas.',
  Browsing: 'Navegação',
  'Follow declaration / brief': 'Seguir declaração / briefing',
  'Declared available': 'Declarada disponível',
  Unavailable: 'Indisponível',
  Forbidden: 'Proibida',
  Delegation: 'Delegação',
  'Adaptive · only if useful': 'Adaptativa · somente se útil',
  'Allow when useful & available': 'Permitir quando útil e disponível',
  'Disabled · work directly': 'Desativada · trabalhar diretamente',
  'Answer language': 'Idioma da resposta',
  'Follow brief · English default': 'Seguir briefing · inglês padrão',
  'The scaffold stays in English. Your original text is preserved without translation.':
    'A estrutura do prompt permanece em inglês. Seu texto original é preservado sem tradução.',
  'Generate prompt': 'Gerar prompt',
  'Regenerate prompt': 'Regenerar prompt',
  'Processed in your browser': 'Processado no seu navegador',
  'Your Astra prompt': 'Seu prompt para o Astra',
  'Waiting for your idea': 'Aguardando sua ideia',
  'Ready to use': 'Pronto para usar',
  'Brief changed': 'Briefing alterado',
  Edited: 'Editado',
  'Good work starts': 'Um bom trabalho começa',
  'with clear instructions.': 'com instruções claras.',
  'Your prompt will appear here,': 'Seu prompt aparecerá aqui,',
  'structured around the task you have in mind.':
    'estruturado em torno da tarefa que você tem em mente.',
  'Your outcome': 'Seu resultado',
  'The context that matters': 'O contexto que importa',
  'Room to take initiative': 'Espaço para tomar iniciativa',
  'A clear finish line': 'Um critério claro de conclusão',
  'Only the structure your task needs':
    'Somente a estrutura que sua tarefa precisa',
  'Why this structure': 'Por que esta estrutura',
  'READY TO COPY': 'PRONTO PARA COPIAR',
  'Click the text to edit': 'Clique no texto para editar',
  'This describes the generated template. Your manual edits may change its structure.':
    'Isto descreve o template gerado. Suas edições manuais podem alterar a estrutura.',
  'Copy prompt': 'Copiar prompt',
  'Download .txt': 'Baixar .txt',
  'Paste into your GPT-6 Astra session and review before running.':
    'Cole na sua sessão do GPT-6 Astra e revise antes de executar.',
  'A prompt builder. Your project runs in Astra.':
    'Um construtor de prompts. Seu projeto é executado no Astra.',
  'Made for a clearer starting point.':
    'Feito para um ponto de partida mais claro.',
  'Based on OpenAI prompting guidance':
    'Baseado nas orientações de prompting da OpenAI',
  'Independent tool · Local rules': 'Ferramenta independente · Regras locais',
  'Your prompt is ready.': 'Seu prompt está pronto.',
  'Example loaded. You can edit it before generating.':
    'Exemplo carregado. Você pode editá-lo antes de gerar.',
  'Prompt copied to clipboard.': 'Prompt copiado para a área de transferência.',
  'Clipboard access is unavailable. The prompt is selected: press Ctrl+C or ⌘C to copy.':
    'O acesso à área de transferência está indisponível. O prompt foi selecionado: pressione Ctrl+C ou ⌘C para copiar.',
  'Prompt downloaded.': 'Prompt baixado.',
  'Please check your brief.': 'Revise seu briefing.',
  'Your brief has changed. Regenerate to apply the new settings.':
    'Seu briefing mudou. Regenere para aplicar as novas configurações.',
  'Auto-detect': 'Detectar automaticamente',
  'Build & code': 'Construção e código',
  Research: 'Pesquisa',
  Writing: 'Texto',
  Strategy: 'Estratégia',
  Data: 'Dados',
  Agent: 'Agente',
  General: 'Geral',
  'Analysis / recommendation': 'Análise / recomendação',
  'Review / diagnosis': 'Revisão / diagnóstico',
  'Plan / roadmap': 'Plano / roteiro',
  'Finished text': 'Texto finalizado',
  'Data analysis': 'Análise de dados',
  'Executed workflow': 'Fluxo executado',
  'Requested answer': 'Resposta solicitada',
  'Working implementation': 'Implementação funcional',
  'Working website': 'Website funcional',
  'Working webapp': 'Webapp funcional',
  'Working app': 'App funcional',
  'Website feasibility analysis': 'Análise de viabilidade do website',
  'App feasibility analysis': 'Análise de viabilidade do app',
  'Repository feasibility analysis': 'Análise de viabilidade do repositório',
  'Feasibility analysis': 'Análise de viabilidade',
  'Website review / diagnosis': 'Revisão / diagnóstico do website',
  'Webapp review / diagnosis': 'Revisão / diagnóstico do webapp',
  'App review / diagnosis': 'Revisão / diagnóstico do app',
  'Repository review / diagnosis': 'Revisão / diagnóstico do repositório',
  English: 'Inglês',
  Portuguese: 'Português',
  Prompt: 'Prompt',
  'English response': 'Resposta em inglês',
  'Portuguese response': 'Resposta em português',
  'Follow brief / English default': 'Seguir briefing / inglês padrão',
};
export function translateUi(language: UiLanguage, value: string): string {
  return language === 'pt' ? (PT_LABELS[value] ?? value) : value;
}
